### ISSUE TITLE
AVL-Baum nicht ausgewogen

### ISSUE THREAD

**Issue by janneskretschmer** [ob-algdati-ws17/blatt-7-aufgabe-1-_-1#1]
im Test "Test_Insert_multiple_different_rotations" (test/TestTree.cpp) füge ich 15 Knoten ein. Wenn der Baum wirklich ausbalanciert wäre, würden alle Elemente in 4 Ebenen passen. Wenn ich die Knoten jedoch in der Reihenfolge aus dem Test einfüge, entstehen 5 Ebenen.
Die unterschiedlichen Fälle sind implementiert, wie in den Folien beschrieben und auch alle getestet. Zudem habe ich es auch auf [dieser Webseite](https://www.cs.usfca.edu/~galles/visualization/AVLtree.html) getestet. Dort hat der Baum auch 5 Ebenen.
Heißt das, dass der Baum nicht in allen Fällen ausbalanciert ist, oder haben die Webseite und ich einen Fehler im Code?
Vielen Dank :)

**Comment by obcode** [comment]
Ich habe mir den Code jetzt noch nicht anschauen können, aber durch die AVL-Eigenschaft bekommen Sie mit 15 Knoten nicht unbedingt einen vollständigen Baum der Höhe 4 (die Blätter fehlen ja).
Die AVL-Eigenschaft stellt nur sicher, dass der Baum nicht zu sehr entartet ist. Ich habe es mal auf der Website durchgespielt. Das Ergebnis

![screenshot 2017-12-11 19 22 48](https://user-images.githubusercontent.com/281558/33846860-ce82265e-dea8-11e7-9ad6-19604179984c.png)

ist definitiv ein AVL-Baum. Es ist kein "perfekter" Baum, aber dazu wären die Umordnungen viel zu aufwändig. In einer anderen Einfügereihenfolge würde man einen "perfekteren" AVL-Baum hinbekommen. Aber dieser ist quasi gut genug.

HTH

**Comment by janneskretschmer** [comment]
Vielen Dank, dann bin ich beruhigt :)
